{{- if .Values.roleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.role.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
