apiVersion: v2
name: steadybit-extension-kubernetes
description: Steadybit Kubernetes extension Helm chart for Kubernetes.
version: 1.6.7
appVersion: v2.6.16
home: https://www.steadybit.com/
icon: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
maintainers:
  - email: daniel.reuter@steadybit.com
    name: reuda
  - email: ansgar.schulte@steadybit.com
    name: ansgarschulte
sources:
  - https://github.com/steadybit/extension-kubernetes
annotations:
  artifacthub.io/images: |
    - name: logo
      image: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
  artifacthub.io/links: |-
    - name: Steadybit website
      url: https://www.steadybit.com
    - name: Steadybit reliability hub
      url: https://hub.steadybit.com
dependencies:
  - name: extensionlib
    version: ^1.4.4
    repository: https://steadybit.github.io/helm-charts
